#!/bin/bash
# lesson5Network/whileLogs
# our comment is here
#echo "The current directory is:"
#pwd
#echo "The user logged in is:"
#whoami

var1=5000
while true
do
        echo "$var1" >> ~/logMy.txt
        echo $var1 >> ~/logMy.txt
        var1=$[ $var1 - 1 ]
        sleep 1
done